name: 'geo_dbt'
version: '1.0.0'
config-version: 2

profile: 'geo_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  geo_dbt:
    +database: GEO_PROJECT
    silver:
      +schema: SILVER
    gold:
      +schema: GOLD
